jobs: 100
cluster: "sbatch -t {resources.time_min} --mem={resources.mem_mb} -n {resources.nodes} --output=slurm/{rule}_{wildcards}_out --error=slurm/{rule}_{wildcards}_error"
default-resources: [nodes=1, mem_mb=3000, time_min=10080]
resources: [nodes=100, mem_mb=1000000]
keep-going: true
latency-wait: 60
restart-times: 3
