input: "input/"

input_beds: "input/beds/"

input_vcfs: "input/vcfs/"

input_genomes: "input/genomes/"

input_lists: "input/lists/"

input_reads: "input/reads/"

output: "output/"

config: "config/config.yaml"

prop: "0.6"  #percent of ovale samples that must meet the coverage threshold to include a given genomic window

cov_filter: "5" #depth of coverage an ovale window must have in order for orthologs within to be included in analysis

all_orthos: "all_pf-poc-pow_orthologs.tsv"

pf_orthos_masked: "ortholog_beds/pf3d7_pf-poc-pow_orthologs_masked.tsv"

poc_orthos_masked: "ortholog_beds/curtisigh01_pf-poc-pow_orthologs_masked.tsv"

pow_orthos_masked: "ortholog_beds/wallikericr01_pf-poc-pow_orthologs_masked.tsv"

pf_orthos_unfiltered: "ortholog_beds/pf3d7_pf-poc-pow_orthologs_unfiltered.tsv"

poc_orthos_unfiltered: "ortholog_beds/curtisigh01_pf-poc-pow_orthologs_unfiltered.tsv"

pow_orthos_unfiltered: "ortholog_beds/wallikericr01_pf-poc-pow_orthologs_unfiltered.tsv"

curtisigh01_genes: "beds/curtisigh01_genes_sorted.bed"

curtisigh01_exons: "beds/curtisigh01_exons_sorted.bed"

wallikericr01_exons: "beds/wallikericr01_exons_sorted.bed"

wallikericr01_genes: "beds/wallikericr01_genes_sorted.bed"

pf3d7_genes: "beds/pf3d7_genes_sorted.bed"

pf3d7_exons: "beds/pf3d7_exons_sorted.bed"

tajima_window: "50"

general_java_opts:                        # ram and threads for less memory intensive gatk tools
  - "-Xms4G"                       # initial heap size
  - "-Xmx4G"                       # maximum heap size
  - "-XX:ParallelGCThreads=2"

gatk_haplotypecaller:
  extra:                                                 # extra options to pass to gatk
    - "--emit-ref-confidence GVCF"                          # mode for emitting reference confidence scores, possible values: {NONE, BP_RESOLUTION, GVCF}
    - "--sample-ploidy 2"                                   # ploidy (no# of chromosomes per sample), for pooled data, set to number of samples in each pool * ploidy) {Default value: 2}
    - "--assembly-region-padding 100"                       # amount of padding (in bp) to add to each side of the active region {Default value: 100}
    - "--min-assembly-region-size 100"                      # minimum size of an assembly region {Default value: 50}
    - "--max-num-haplotypes-in-population 128"              # maximum number of haplotypes in population {Default value: 128}
    - "--kmer-size 10"                                      # kmer size to use in the read threading assembler {Default value: 10}
    - "--kmer-size 25"                                      # kmer size to use in the read threading assembler {Default value: 25}
    - "--min-dangling-branch-length 4"                      # minimum length of a dangling branch to try to recover {Default value: 4}
    - "--heterozygosity 0.001"                             # heterozygosity for SNP and indel calling {Default value: 0.001, Kevin Wamae uses 0.0029 in Pf variant calling}
    - "--indel-heterozygosity 1.25E-4"                       # heterozygosity for indel calling {Default value: 1.25E-4, Kevin Wamae uses 0.0017 for Pf}
    - "--disable-read-filter null"                          # read filters to be disabled before analysis
    - "--min-base-quality-score 10"                         # minimum base quality required to consider a base for calling {Default value: 10}
    - "--base-quality-score-threshold 18"                   # base qualities below this threshold will be reduced to the minimum {Default value: 18}
  java:
    - "-Xms20G"                       # optimal mem=20G
    - "-Xmx20G"                       # optimal mem=20G
    - "-XX:ParallelGCThreads=2"      # optimal threads=2

gatk_genotypegvcfs:
  java:
    - "-Xms2G"                       # optimal mem=2G
    - "-Xmx2G"                       # optimal mem=2G
    - "-XX:ParallelGCThreads=2"      # optimal threads=2

gatk_hardfiltersnps:
  - '--filter-name "QD3" --filter-expression "QD<3.0"'
  - '--filter-name "FS50" --filter-expression "FS>50.0"'
  - '--filter-name "SOR3" --filter-expression "SOR > 3.0"'
  - '--filter-name "MQ50" --filter-expression "MQ<50.0"'
  - '--filter-name "MQRS-2.5" --filter-expression "MQRankSum<-2.5"'
  - '--filter-name "RPRS-3" --filter-expression "ReadPosRankSum<-3.0"'

realmccoilr:
  maxcoi: "25"
  threshold_ind: "10"
  threshold_site: "10"
  totalrun: "1000"
  burnin: "100"

plink:
  window: "50" #in number of variants
  step: "5" #number of variants
  r2: "0.3"
